### ISSUE TITLE
[BUG] unable to display power limit

### ISSUE THREAD

**Issue by liblaf** [XuehaiPan/nvitop#86]
### Required prerequisites

- [X] I have read the documentation <https://nvitop.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/XuehaiPan/nvitop/issues) that this hasn't already been reported. (comment there if it has.)
- [X] I have tried the latest version of nvitop in a new isolated virtual environment.

### What version of nvitop are you using?

1.2.0

### Operating system and version

Arch Linux x86_64

### NVIDIA driver version

535.86.05

### NVIDIA-SMI

```text
Fri Aug  4 16:37:22 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.86.05              Driver Version: 535.86.05    CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4060 ...    Off | 00000000:01:00.0 Off |                  N/A |
| N/A   34C    P8               2W / 115W |     25MiB /  8188MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      2072      G   /usr/lib/Xorg                                20MiB |
+---------------------------------------------------------------------------------------+
```

###### Installation

```shell
pipx install nvitop
```

###### Python version & relevant libraries

```
3.11.3 (main, Jun  5 2023, 09:32:32) [GCC 13.1.1 20230429] linux
nvidia-ml-py==11.525.131
nvitop==1.2.0
```

### Problem description

`nvitop` cannot display power limit correctly.

```shell
$ nvitop --once
Fri Aug 04 16:42:38 2023
╒═════════════════════════════════════════════════════════════════════════════╕
│ NVITOP 1.2.0       Driver Version: 535.86.05      CUDA Driver Version: 12.2 │
├───────────────────────────────┬──────────────────────┬──────────────────────┤
│ GPU  Name        Persistence-M│ Bus-Id        Disp.A │ Volatile Uncorr. ECC │
│ Fan  Temp  Perf  Pwr:Usage/Cap│         Memory-Usage │ GPU-Util  Compute M. │
╞═══════════════════════════════╪══════════════════════╪══════════════════════╡
│   0  .. 4060 Laptop GPU  Off  │ 00000000:01:00.0 Off │                  N/A │
│ N/A   38C    P8      2W / N/A │      26MiB / 8188MiB │      0%      Default │
╘═══════════════════════════════╧══════════════════════╧══════════════════════╛
```

### Steps to Reproduce

Command lines:

```bash
nvitop --once
```

### Logs

```text
[DEBUG] 2023-08-04 16:43:45,692 nvitop.api.libnvml::__determine_get_memory_info_version_suffix: NVML get memory info version 2 is available.
[DEBUG] 2023-08-04 16:43:45,694 nvitop.api.libnvml::__determine_get_running_processes_version_suffix: NVML get running process version 3 API with v3 type struct is available.
```

### Expected behavior

`nvitop` should display power limit as `nvidia-smi`.

**Comment by XuehaiPan** [comment]
Hi @liblaf, thanks for raising this issue.

Could you try the following code in your Python REPL?

```python
$ python3
>>> from nvitop import *
>>> d = Device(0)
>>> libnvml.nvmlDeviceGetPowerUsage(d.handle)  # power usage in milliwatts (mW)
59085
>>> d.power_usage()  # power usage in milliwatts (mW)
59147
>>> libnvml.nvmlDeviceGetPowerManagementLimit(d.handle)  # power limit in milliwatts (mW)
400000
>>> d.power_limit()  # power limit in milliwatts (mW)
400000
```

Then we can dive deeper into this error.

**Comment by liblaf** [comment]
```python
$ ${HOME}/.local/pipx/venvs/nvitop/bin/python
Python 3.11.3 (main, Jun  5 2023, 09:32:32) [GCC 13.1.1 20230429] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from nvitop import *
>>> d = Device(0)
>>> libnvml.nvmlDeviceGetPowerUsage(d.handle)  # power usage in milliwatts (mW)
2348
>>> d.power_usage()  # power usage in milliwatts (mW)
2347
>>> libnvml.nvmlDeviceGetPowerManagementLimit(d.handle)  # power limit in milliwatts (mW)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/liblaf/.local/pipx/venvs/nvitop/lib/python3.11/site-packages/pynvml.py", line 2394, in nvmlDeviceGetPowerManagementLimit
    _nvmlCheckReturn(ret)
  File "/home/liblaf/.local/pipx/venvs/nvitop/lib/python3.11/site-packages/pynvml.py", line 855, in _nvmlCheckReturn
    raise NVMLError(ret)
pynvml.NVMLError_NotSupported: Not Supported
>>> d.power_limit()  # power limit in milliwatts (mW)
'N/A'
```

**Comment by liblaf** [comment]
i tried to install the latest `nvidia-ml-py==12.535.77` but it produces the same error.

**Comment by liblaf** [comment]
indeed

```shell
$ nvidia-smi --query-gpu=index,power.management,power.draw,power.limit --format=csv
index, power.management, power.draw [W], power.limit [W]
0, [N/A], 2.55 W, [N/A]
```
